export { default as javascript } from './javascript.png'
export { default as css } from './css.png'
export { default as html } from './html.png'
export { default as tailwind  } from './tailwind.png'
export { default as reacts } from './react.png'
export { default as github } from './github.png'
export { default as profile } from './1.jpg'
export {default as ruby} from './download.png'
